CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date DATE NOT NULL,
    sale_value NUMERIC(15, 2) NOT NULL,
    seller_id BIGINT NOT NULL,
    seller_name VARCHAR(120) NOT NULL
);

CREATE INDEX idx_sales_sale_date ON sales (sale_date);
CREATE INDEX idx_sales_seller_id ON sales (seller_id);
